#!/usr/bin/perl
#
# Mon Oct 18 22:10:29 CEST 2004
# docelic@icdevgroup.org
#
# Simple script to extract Perl code out of combined files like 
# UserTags or Filters.
#
# Example use:
# for p in *.filter; do pcode $p | perl -c; done
# 

while (<>) {
	next if /Routine\s+<<(\S+)/ and $run=$1  or  /^$run$/ and $run=0;
	print if $run;
}

